### ISSUE TITLE
Trying to get particle to publish an event.

### ISSUE THREAD

**Issue by bklavet** [rlisle/alexaParticleBridge#1]
Hello rlisle,
I have duplicated your project here to the best of my ability and I can send a test call from the Alexa Developer Test portal to the aws lambda function and get the expected response.  I have loaded the Arduino example.ino to the particle and added a Particle.publish ("It works."); . 
My hope was to see a published event in the Console Log when the alexa skill is tested through the developer portal.  However I am unable to get a published log from aws lambda calls.  I then removed the example and replaced with nothing.
void setup(){}
void loop(){}
and was still able to test from the alexa developer portal to aws lambda and get the successful response from my aws lambda function.

Why is this not talking to the particle and still acting happy?  Shouldn't I be getting and endpoint error.
this is how I modified the example.  any ideas?

void setup() {
  Serial.begin(57600)
  Serial.println("ParticleExample started.")
  
  Particle.function("myFunction",myFunction);
}

void loop() {
  // put your main code here, to run repeatedly:

}

int myFunction(String command) {
    Serial.println("myFunction called.");
    Particle.publish("itWorked");
    // We don't need to return anything.
    // Just return an easy to recognize number for testing
    return 123;   
}

**Comment by bklavet** [comment]
Alright, figured out what I had wrong,  I had the incorrect access token.

**Comment by rlisle** [comment]
Glad to hear it. I'll be releasing additional code that adds iOS support and an Alexa Smart Home skill shortly.
